apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: hello-eck
spec:
  version: 7.3.0
  nodes:
  - name: mixed-large
    nodeCount: 3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # note: elasticsearch-data must be the name of the Elasticsearch volume
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: hello-kibana
spec:
  version: 7.3.0
  nodeCount: 1
  elasticsearchRef:
    name: "hello-eck"
  http:
    tls:
      certificate:
        secretName: pebrc-ovh-tls
