apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hot-nodes
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: warm-nodes
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard

